# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from escrow.v1 import escrow_pb2 as escrow_dot_v1_dot_escrow__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in escrow/v1/escrow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EscrowStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/escrow.v1.Escrow/Ping',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.PingRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.PingResponse.FromString,
                _registered_method=True)
        self.OpenScope = channel.unary_unary(
                '/escrow.v1.Escrow/OpenScope',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.OpenScopeRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.OpenScopeResponse.FromString,
                _registered_method=True)
        self.CloseScope = channel.unary_unary(
                '/escrow.v1.Escrow/CloseScope',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.CloseScopeRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
                _registered_method=True)
        self.Decide = channel.unary_unary(
                '/escrow.v1.Escrow/Decide',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.DecideRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
                _registered_method=True)
        self.SettleUnscoped = channel.unary_unary(
                '/escrow.v1.Escrow/SettleUnscoped',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.SettleUnscopedRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
                _registered_method=True)
        self.GetChangeSet = channel.unary_unary(
                '/escrow.v1.Escrow/GetChangeSet',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.GetChangeSetRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
                _registered_method=True)
        self.AwaitDecision = channel.unary_stream(
                '/escrow.v1.Escrow/AwaitDecision',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.AwaitDecisionRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
                _registered_method=True)


class EscrowServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Liveness and version handshake.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenScope(self, request, context):
        """Open a scope: snapshot at open, a virtual root under /escrow/<scope_id>/. In a
        session that has a scope held with a wait (Outcome.wait), the call waits for that
        scope's verdict; at the client's deadline it fails with FAILED_PRECONDITION naming
        the held scope, which stays held.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseScope(self, request, context):
        """Close a scope: the caller has fsynced its open files; the daemon stops the
        scope's sandboxes, freezes the scope and returns its change set. Close, Decide
        and the exec socket need the scope's token (from OpenScope); a missing or wrong
        token fails with PERMISSION_DENIED. The unscoped scope has no token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decide(self, request, context):
        """Apply the close-time decision: commit, discard or return to agent. The verdict is
        the opener's proposal and only tightens the review's (ChangeSet.review): a commit
        or a return of a change set the software tier discarded is a discard, and a commit
        of one that needs a tier above software holds the scope for those reviewers
        (OUTCOME_STATUS_HELD). A held scope is the reviewers' to decide: its opener can
        only discard (withdraw) it; a commit or a return fails with PERMISSION_DENIED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleUnscoped(self, request, context):
        """Close the implicit default scope (unscoped = implicit) and return its change
        set; decide it like any scope (scope id "unscoped"). After a commit or a
        discard the daemon opens a fresh default scope at the same path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangeSet(self, request, context):
        """The change set of a closed, undecided scope, diff included, without closing
        anything: an open scope fails with FAILED_PRECONDITION. For `escrow diff`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitDecision(self, request, context):
        """Follow a held scope (Decide returned OUTCOME_STATUS_HELD) to its verdict: an
        OUTCOME_STATUS_HELD outcome now and after each tier's review (`tiers` the ones
        still to review), then the final outcome, and the stream ends. A scope decided
        already gets its last outcome; one that is not held fails with
        FAILED_PRECONDITION. Needs the scope's token, like Decide.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EscrowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.PingRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.PingResponse.SerializeToString,
            ),
            'OpenScope': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenScope,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.OpenScopeRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.OpenScopeResponse.SerializeToString,
            ),
            'CloseScope': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseScope,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.CloseScopeRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.SerializeToString,
            ),
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.DecideRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.Outcome.SerializeToString,
            ),
            'SettleUnscoped': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleUnscoped,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.SettleUnscopedRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.SerializeToString,
            ),
            'GetChangeSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangeSet,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.GetChangeSetRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.ChangeSet.SerializeToString,
            ),
            'AwaitDecision': grpc.unary_stream_rpc_method_handler(
                    servicer.AwaitDecision,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.AwaitDecisionRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.Outcome.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'escrow.v1.Escrow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('escrow.v1.Escrow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Escrow:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/Ping',
            escrow_dot_v1_dot_escrow__pb2.PingRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/OpenScope',
            escrow_dot_v1_dot_escrow__pb2.OpenScopeRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.OpenScopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/CloseScope',
            escrow_dot_v1_dot_escrow__pb2.CloseScopeRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/Decide',
            escrow_dot_v1_dot_escrow__pb2.DecideRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettleUnscoped(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/SettleUnscoped',
            escrow_dot_v1_dot_escrow__pb2.SettleUnscopedRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangeSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Escrow/GetChangeSet',
            escrow_dot_v1_dot_escrow__pb2.GetChangeSetRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.ChangeSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwaitDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/escrow.v1.Escrow/AwaitDecision',
            escrow_dot_v1_dot_escrow__pb2.AwaitDecisionRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReviewerStub:
    """Served on `<ESCROW_SOCKET>.review` only.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListHeld = channel.unary_unary(
                '/escrow.v1.Reviewer/ListHeld',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.ListHeldRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.ListHeldResponse.FromString,
                _registered_method=True)
        self.GetHeld = channel.unary_unary(
                '/escrow.v1.Reviewer/GetHeld',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.GetHeldRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.GetHeldResponse.FromString,
                _registered_method=True)
        self.Review = channel.unary_unary(
                '/escrow.v1.Reviewer/Review',
                request_serializer=escrow_dot_v1_dot_escrow__pb2.ReviewRequest.SerializeToString,
                response_deserializer=escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
                _registered_method=True)


class ReviewerServicer:
    """Served on `<ESCROW_SOCKET>.review` only.
    """

    def ListHeld(self, request, context):
        """The held scopes, oldest hold first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeld(self, request, context):
        """A held scope: its change set with writers and diff, its tiers' verdicts so far
        and its session's earlier decisions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Review(self, request, context):
        """A tier's verdict on a held scope. The tier must be one the scope still waits
        for; a human's verdict also stands for the cheaper tiers still pending. Verdicts
        only tighten (commit < return < discard): a looser verdict than the one so far
        fails with PERMISSION_DENIED unless the tier is human and `override` is set,
        which the ledger records. After the last pending tier the scope is decided with
        the verdict so far, as Decide would (a commit can conflict); before it, the
        outcome is OUTCOME_STATUS_HELD with the tiers left.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListHeld': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHeld,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.ListHeldRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.ListHeldResponse.SerializeToString,
            ),
            'GetHeld': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeld,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.GetHeldRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.GetHeldResponse.SerializeToString,
            ),
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=escrow_dot_v1_dot_escrow__pb2.ReviewRequest.FromString,
                    response_serializer=escrow_dot_v1_dot_escrow__pb2.Outcome.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'escrow.v1.Reviewer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('escrow.v1.Reviewer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Reviewer:
    """Served on `<ESCROW_SOCKET>.review` only.
    """

    @staticmethod
    def ListHeld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Reviewer/ListHeld',
            escrow_dot_v1_dot_escrow__pb2.ListHeldRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.ListHeldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHeld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Reviewer/GetHeld',
            escrow_dot_v1_dot_escrow__pb2.GetHeldRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.GetHeldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.v1.Reviewer/Review',
            escrow_dot_v1_dot_escrow__pb2.ReviewRequest.SerializeToString,
            escrow_dot_v1_dot_escrow__pb2.Outcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
